/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.tap_u3tv.ui;

import com.mycompany.tap_u3tv.classes.DBManager;
import com.mycompany.tap_u3tv.classes.JSONManager;
import com.mycompany.tap_u3tv.classes.Theme;
import com.mycompany.tap_u3tv.classes.User;
import java.awt.Color;
import java.awt.Cursor;
import java.awt.GridLayout;
import java.awt.Image;
import java.util.ArrayList;
import java.util.Collections;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

/**
 *
 * @author angel
 */
public class ForumFrame extends javax.swing.JFrame {

    private ArrayList<User> users;
    private int userLogged;
    private User userAux;
    private ArrayList<Theme> themes;
    private GridLayout gridLayout = new GridLayout(1, 1);

    /**
     * Creates new form ForumFrame
     */
    public ForumFrame() {
        initComponents();
    }

    public ForumFrame(int userId) {
        initComponents();
        setLocationRelativeTo(null);
        this.userLogged = userId;

        try {
            users = DBManager.getUsers();
            userLogged = userId;

            this.themes = DBManager.readThemes();

            container.setLayout(gridLayout);
            scrollPane.getVerticalScrollBar().setUnitIncrement(16);
        } catch (Exception e) {
            e.printStackTrace();
        }

        displayUserInfo(userId);
        displayThemes();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        textFieldRound1 = new org.edisoncor.gui.textField.TextFieldRound();
        panelImage1 = new org.edisoncor.gui.panel.PanelImage();
        jPanel2 = new javax.swing.JPanel();
        imgUser = new org.edisoncor.gui.panel.PanelImage();
        jSeparator1 = new javax.swing.JSeparator();
        labelLogout = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        panelImage2 = new org.edisoncor.gui.panel.PanelImage();
        jPanel5 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        panelImage3 = new org.edisoncor.gui.panel.PanelImage();
        jPanel6 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        panelImage4 = new org.edisoncor.gui.panel.PanelImage();
        labelUser = new javax.swing.JLabel();
        scrollPane = new javax.swing.JScrollPane();
        container = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(251, 251, 251));
        setPreferredSize(new java.awt.Dimension(1110, 690));
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(217, 217, 217), 2));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Source Sans Pro SemiBold", 0, 32)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(11, 77, 212));
        jLabel2.setText("Therum");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 40, -1, -1));

        textFieldRound1.setBackground(new java.awt.Color(251, 251, 251));
        textFieldRound1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(217, 217, 217), 2, true));
        textFieldRound1.setForeground(new java.awt.Color(0, 0, 0));
        textFieldRound1.setText("    Search");
        textFieldRound1.setFont(new java.awt.Font("Source Sans Pro", 0, 16)); // NOI18N
        textFieldRound1.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                textFieldRound1FocusGained(evt);
            }
        });
        jPanel1.add(textFieldRound1, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 50, 780, 30));

        panelImage1.setIcon(new javax.swing.ImageIcon("C:\\Users\\angel\\Pictures\\Therum\\icons8-search-50(1).png")); // NOI18N
        panelImage1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                panelImage1MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                panelImage1MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                panelImage1MouseExited(evt);
            }
        });

        javax.swing.GroupLayout panelImage1Layout = new javax.swing.GroupLayout(panelImage1);
        panelImage1.setLayout(panelImage1Layout);
        panelImage1Layout.setHorizontalGroup(
            panelImage1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 30, Short.MAX_VALUE)
        );
        panelImage1Layout.setVerticalGroup(
            panelImage1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 30, Short.MAX_VALUE)
        );

        jPanel1.add(panelImage1, new org.netbeans.lib.awtextra.AbsoluteConstraints(990, 50, 30, 30));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(-20, -10, 1160, 110));

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        imgUser.setOpaque(false);
        imgUser.setPreferredSize(new java.awt.Dimension(100, 100));
        imgUser.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                imgUserMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                imgUserMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                imgUserMouseExited(evt);
            }
        });

        javax.swing.GroupLayout imgUserLayout = new javax.swing.GroupLayout(imgUser);
        imgUser.setLayout(imgUserLayout);
        imgUserLayout.setHorizontalGroup(
            imgUserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        imgUserLayout.setVerticalGroup(
            imgUserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        jPanel2.add(imgUser, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 40, -1, -1));

        jSeparator1.setBackground(new java.awt.Color(217, 217, 217));
        jSeparator1.setForeground(new java.awt.Color(217, 217, 217));
        jSeparator1.setOrientation(javax.swing.SwingConstants.VERTICAL);
        jPanel2.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(308, 10, 10, 530));

        labelLogout.setFont(new java.awt.Font("Questrial", 0, 28)); // NOI18N
        labelLogout.setForeground(new java.awt.Color(11, 77, 212));
        labelLogout.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelLogout.setText("Log out");
        labelLogout.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                labelLogoutMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                labelLogoutMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                labelLogoutMouseExited(evt);
            }
        });
        jPanel2.add(labelLogout, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 420, 300, -1));

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jPanel3MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jPanel3MouseExited(evt);
            }
        });
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Source Sans Pro SemiBold", 0, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(30, 30, 30));
        jLabel1.setText("News feed");
        jPanel3.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(103, 4, -1, -1));

        jPanel4.setBackground(new java.awt.Color(11, 77, 212));

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 10, Short.MAX_VALUE)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 40, Short.MAX_VALUE)
        );

        jPanel3.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 10, 40));

        panelImage2.setIcon(new javax.swing.ImageIcon("C:\\Users\\angel\\Pictures\\Therum\\i-feed.png")); // NOI18N
        panelImage2.setOpaque(false);

        javax.swing.GroupLayout panelImage2Layout = new javax.swing.GroupLayout(panelImage2);
        panelImage2.setLayout(panelImage2Layout);
        panelImage2Layout.setHorizontalGroup(
            panelImage2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 30, Short.MAX_VALUE)
        );
        panelImage2Layout.setVerticalGroup(
            panelImage2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 30, Short.MAX_VALUE)
        );

        jPanel3.add(panelImage2, new org.netbeans.lib.awtextra.AbsoluteConstraints(66, 4, 30, 30));

        jPanel2.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 210, 290, 40));

        jPanel5.setBackground(new java.awt.Color(255, 255, 255));
        jPanel5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanel5MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jPanel5MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jPanel5MouseExited(evt);
            }
        });
        jPanel5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setFont(new java.awt.Font("Source Sans Pro SemiBold", 0, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(30, 30, 30));
        jLabel3.setText("New Theme");
        jPanel5.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(103, 4, -1, -1));

        panelImage3.setIcon(new javax.swing.ImageIcon("C:\\Users\\angel\\Pictures\\Therum\\i-edit.png")); // NOI18N
        panelImage3.setOpaque(false);
        panelImage3.setPreferredSize(new java.awt.Dimension(30, 30));

        javax.swing.GroupLayout panelImage3Layout = new javax.swing.GroupLayout(panelImage3);
        panelImage3.setLayout(panelImage3Layout);
        panelImage3Layout.setHorizontalGroup(
            panelImage3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 30, Short.MAX_VALUE)
        );
        panelImage3Layout.setVerticalGroup(
            panelImage3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 30, Short.MAX_VALUE)
        );

        jPanel5.add(panelImage3, new org.netbeans.lib.awtextra.AbsoluteConstraints(66, 4, 30, 30));

        jPanel2.add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 260, 290, 40));

        jPanel6.setBackground(new java.awt.Color(255, 255, 255));
        jPanel6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanel6MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jPanel6MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jPanel6MouseExited(evt);
            }
        });
        jPanel6.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel4.setFont(new java.awt.Font("Source Sans Pro SemiBold", 0, 24)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(30, 30, 30));
        jLabel4.setText("Export PDF");
        jPanel6.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(103, 4, -1, -1));

        panelImage4.setIcon(new javax.swing.ImageIcon("C:\\Users\\angel\\Pictures\\Therum\\i-pdf.png")); // NOI18N
        panelImage4.setOpaque(false);
        panelImage4.setPreferredSize(new java.awt.Dimension(30, 30));

        javax.swing.GroupLayout panelImage4Layout = new javax.swing.GroupLayout(panelImage4);
        panelImage4.setLayout(panelImage4Layout);
        panelImage4Layout.setHorizontalGroup(
            panelImage4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 30, Short.MAX_VALUE)
        );
        panelImage4Layout.setVerticalGroup(
            panelImage4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 30, Short.MAX_VALUE)
        );

        jPanel6.add(panelImage4, new org.netbeans.lib.awtextra.AbsoluteConstraints(66, 4, 30, 30));

        jPanel2.add(jPanel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 308, 290, 40));

        labelUser.setFont(new java.awt.Font("Questrial", 0, 28)); // NOI18N
        labelUser.setForeground(new java.awt.Color(11, 77, 212));
        labelUser.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelUser.setText("Recent Logged");
        labelUser.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                labelUserMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                labelUserMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                labelUserMouseExited(evt);
            }
        });
        jPanel2.add(labelUser, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 160, 300, -1));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 100, 310, 590));

        scrollPane.setBackground(new java.awt.Color(251, 251, 251));
        scrollPane.setBorder(null);
        scrollPane.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_ALWAYS);
        scrollPane.setHorizontalScrollBar(null);

        container.setBackground(new java.awt.Color(238, 238, 238));

        javax.swing.GroupLayout containerLayout = new javax.swing.GroupLayout(container);
        container.setLayout(containerLayout);
        containerLayout.setHorizontalGroup(
            containerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 810, Short.MAX_VALUE)
        );
        containerLayout.setVerticalGroup(
            containerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 560, Short.MAX_VALUE)
        );

        scrollPane.setViewportView(container);

        getContentPane().add(scrollPane, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 100, 800, 560));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void textFieldRound1FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_textFieldRound1FocusGained
        textFieldRound1.setText("");
    }//GEN-LAST:event_textFieldRound1FocusGained

    private void panelImage1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelImage1MouseEntered
        setCursor(Cursor.HAND_CURSOR);
    }//GEN-LAST:event_panelImage1MouseEntered

    private void panelImage1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelImage1MouseExited
        setCursor(DEFAULT_CURSOR);
    }//GEN-LAST:event_panelImage1MouseExited

    private void jPanel3MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel3MouseEntered
        jPanel3.setBackground(Color.decode("#F5F5F5"));
        setCursor(Cursor.HAND_CURSOR);
    }//GEN-LAST:event_jPanel3MouseEntered

    private void jPanel3MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel3MouseExited
        jPanel3.setBackground(Color.decode("#FFFFFF"));
        setCursor(DEFAULT_CURSOR);
    }//GEN-LAST:event_jPanel3MouseExited

    private void jPanel5MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel5MouseEntered
        jPanel5.setBackground(Color.decode("#F5F5F5"));
        setCursor(Cursor.HAND_CURSOR);
    }//GEN-LAST:event_jPanel5MouseEntered

    private void jPanel5MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel5MouseExited
        jPanel5.setBackground(Color.decode("#FFFFFF"));
        setCursor(DEFAULT_CURSOR);
    }//GEN-LAST:event_jPanel5MouseExited

    private void jPanel6MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel6MouseEntered
        jPanel6.setBackground(Color.decode("#F5F5F5"));
        setCursor(Cursor.HAND_CURSOR);
    }//GEN-LAST:event_jPanel6MouseEntered

    private void jPanel6MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel6MouseExited
        jPanel6.setBackground(Color.decode("#FFFFFF"));
        setCursor(DEFAULT_CURSOR);
    }//GEN-LAST:event_jPanel6MouseExited

    private void labelLogoutMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_labelLogoutMouseClicked
        dispose();
        new LoginFrame().setVisible(true);
    }//GEN-LAST:event_labelLogoutMouseClicked

    private void jPanel5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel5MouseClicked
        try {
            if ((DBManager.countUserPost(userLogged) - DBManager.countUserComments(userLogged)) < 3) {
                new NewTheme(userLogged, this).setVisible(true);
            } else {
                JOptionPane.showMessageDialog(null, "You need to do a comment, before any posting");
            }
        } catch (Exception e) {
            e.printStackTrace();
        }
    }//GEN-LAST:event_jPanel5MouseClicked

    private void labelLogoutMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_labelLogoutMouseEntered
        setCursor(HAND_CURSOR);
    }//GEN-LAST:event_labelLogoutMouseEntered

    private void labelLogoutMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_labelLogoutMouseExited
        setCursor(DEFAULT_CURSOR);
    }//GEN-LAST:event_labelLogoutMouseExited

    private void imgUserMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_imgUserMouseEntered
        setCursor(Cursor.HAND_CURSOR);
    }//GEN-LAST:event_imgUserMouseEntered

    private void imgUserMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_imgUserMouseExited
        setCursor(DEFAULT_CURSOR);
    }//GEN-LAST:event_imgUserMouseExited

    private void labelUserMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_labelUserMouseEntered
        setCursor(HAND_CURSOR);
    }//GEN-LAST:event_labelUserMouseEntered

    private void labelUserMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_labelUserMouseExited
        setCursor(DEFAULT_CURSOR);
    }//GEN-LAST:event_labelUserMouseExited

    private void labelUserMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_labelUserMouseClicked
        dispose();
        new ProfileFrame(userLogged, userLogged).setVisible(true);
    }//GEN-LAST:event_labelUserMouseClicked

    private void imgUserMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_imgUserMouseClicked
        dispose();
        new ProfileFrame(userLogged, userLogged).setVisible(true);
    }//GEN-LAST:event_imgUserMouseClicked

    private void jPanel6MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel6MouseClicked
        JSONManager.exportToPDF();
    }//GEN-LAST:event_jPanel6MouseClicked

    private void panelImage1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelImage1MouseClicked
        try {
            themes = DBManager.search(textFieldRound1.getText());
            displayThemes();
        } catch (Exception e) {
            e.printStackTrace();
        }
    }//GEN-LAST:event_panelImage1MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ForumFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ForumFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ForumFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ForumFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ForumFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel container;
    private org.edisoncor.gui.panel.PanelImage imgUser;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel labelLogout;
    private javax.swing.JLabel labelUser;
    private org.edisoncor.gui.panel.PanelImage panelImage1;
    private org.edisoncor.gui.panel.PanelImage panelImage2;
    private org.edisoncor.gui.panel.PanelImage panelImage3;
    private org.edisoncor.gui.panel.PanelImage panelImage4;
    private javax.swing.JScrollPane scrollPane;
    private org.edisoncor.gui.textField.TextFieldRound textFieldRound1;
    // End of variables declaration//GEN-END:variables

    private void displayUserInfo(int userId) {
        for (User user : users) {
            if (user.getId() == userId) {
                userAux = user;
                Image originalImg = new ImageIcon(user.getPfpPath()).getImage();
                imgUser.setIcon(new ImageIcon(originalImg.getScaledInstance(100, 100, Image.SCALE_SMOOTH)));
                repaint();
                labelUser.setText(user.getName());

                if (user.isIsAdmin()) {
                    jPanel6.setEnabled(true);
                    jPanel6.setVisible(true);
                } else {
                    jPanel6.setEnabled(false);
                    jPanel6.setVisible(false);
                }
            }
        }
    }

    public void displayThemes() {
        container.removeAll();

        Collections.reverse(themes);

        themes.stream().forEach(theme -> {
            gridLayout.setRows(gridLayout.getRows() + 1);
            users.stream().filter(user -> (theme.getUserdId() == user.getId())).forEach(user -> {
                ThemePanel panel = new ThemePanel(theme, user, userAux, this);
                container.add(panel);
                container.updateUI();
            });
        });
    }
}
