/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.tap_u3tv.ui;

import com.mycompany.tap_u3tv.classes.DBManager;
import com.mycompany.tap_u3tv.classes.JSONManager;
import com.mycompany.tap_u3tv.classes.User;
import java.awt.Color;
import java.awt.Cursor;
import java.awt.Image;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import java.awt.event.MouseListener;
import java.util.ArrayList;
import java.util.regex.Pattern;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

/**
 *
 * @author angel
 */
public class LoginFrame extends javax.swing.JFrame {

    private ArrayList<User> users;
    private ArrayList<User> recentUsers;

    /**
     * Creates new form LoginFrame
     */
    public LoginFrame() {
        initComponents();
        setLocationRelativeTo(null);

        try {
            users = DBManager.getUsers();
            recentUsers = JSONManager.getRecentUsers();
        } catch (Exception e) {
            e.printStackTrace();
        }

        displayRecentUsers();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panel1 = new org.edisoncor.gui.panel.Panel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        emailField = new javax.swing.JTextField();
        passwordField = new javax.swing.JPasswordField();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        btnSignUp = new javax.swing.JLabel();
        btnEnter = new javax.swing.JLabel();
        jCheckBox1 = new javax.swing.JCheckBox();
        jLabel5 = new javax.swing.JLabel();
        labelUser = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        imgUser1 = new org.edisoncor.gui.panel.PanelImage();
        jLabel8 = new javax.swing.JLabel();
        labelUser2 = new javax.swing.JLabel();
        imgUser2 = new org.edisoncor.gui.panel.PanelImage();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));
        setResizable(false);
        setSize(new java.awt.Dimension(1512, 982));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        panel1.setColorPrimario(new java.awt.Color(16, 81, 213));
        panel1.setColorSecundario(new java.awt.Color(47, 132, 252));
        panel1.setPreferredSize(new java.awt.Dimension(470, 682));

        jLabel1.setFont(new java.awt.Font("Source Sans Pro SemiBold", 0, 32)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Log in");

        jLabel2.setFont(new java.awt.Font("Source Sans Pro SemiBold", 0, 32)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Therum");

        jLabel3.setFont(new java.awt.Font("Questrial", 0, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Password");

        jLabel4.setFont(new java.awt.Font("Questrial", 0, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Email");

        emailField.setFont(new java.awt.Font("Questrial", 0, 18)); // NOI18N
        emailField.setForeground(new java.awt.Color(204, 204, 204));
        emailField.setText("email_cool@email.com");
        emailField.setBorder(null);
        emailField.setOpaque(false);
        emailField.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                emailFieldFocusGained(evt);
            }
        });

        passwordField.setFont(new java.awt.Font("Questrial", 0, 18)); // NOI18N
        passwordField.setForeground(new java.awt.Color(204, 204, 204));
        passwordField.setText("jPasswordField1");
        passwordField.setBorder(null);
        passwordField.setOpaque(false);
        passwordField.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                passwordFieldFocusGained(evt);
            }
        });

        jSeparator1.setBackground(new java.awt.Color(255, 255, 255));

        jSeparator2.setBackground(new java.awt.Color(255, 255, 255));

        btnSignUp.setIcon(new javax.swing.ImageIcon("C:\\Users\\angel\\Pictures\\Therum\\new-acc.png")); // NOI18N
        btnSignUp.setPreferredSize(new java.awt.Dimension(78, 48));
        btnSignUp.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnSignUpMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnSignUpMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnSignUpMouseExited(evt);
            }
        });

        btnEnter.setIcon(new javax.swing.ImageIcon("C:\\Users\\angel\\Pictures\\Therum\\enter-btn.png")); // NOI18N
        btnEnter.setPreferredSize(new java.awt.Dimension(78, 48));
        btnEnter.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnEnterMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnEnterMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnEnterMouseExited(evt);
            }
        });

        jCheckBox1.setFont(new java.awt.Font("Questrial", 0, 12)); // NOI18N
        jCheckBox1.setForeground(new java.awt.Color(255, 255, 255));
        jCheckBox1.setText("Remember account?");
        jCheckBox1.setOpaque(false);

        javax.swing.GroupLayout panel1Layout = new javax.swing.GroupLayout(panel1);
        panel1.setLayout(panel1Layout);
        panel1Layout.setHorizontalGroup(
            panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel1Layout.createSequentialGroup()
                .addGap(48, 48, 48)
                .addGroup(panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(jLabel1)
                    .addComponent(jLabel4)
                    .addComponent(jLabel3)
                    .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 353, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(emailField, javax.swing.GroupLayout.PREFERRED_SIZE, 355, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(panel1Layout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addGroup(panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jCheckBox1)
                            .addGroup(panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(passwordField)
                                .addComponent(jSeparator1)
                                .addComponent(btnSignUp, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btnEnter, javax.swing.GroupLayout.PREFERRED_SIZE, 355, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(34, Short.MAX_VALUE))
        );
        panel1Layout.setVerticalGroup(
            panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel1Layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addComponent(jLabel2)
                .addGap(77, 77, 77)
                .addComponent(jLabel1)
                .addGap(61, 61, 61)
                .addComponent(jLabel4)
                .addGap(18, 18, 18)
                .addGroup(panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panel1Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(emailField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(51, 51, 51)
                .addComponent(jLabel3)
                .addGap(20, 20, 20)
                .addComponent(passwordField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jCheckBox1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 39, Short.MAX_VALUE)
                .addComponent(btnEnter, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnSignUp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(56, 56, 56))
        );

        getContentPane().add(panel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 440, 690));

        jLabel5.setFont(new java.awt.Font("Source Sans Pro Light", 0, 16)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(11, 77, 212));
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("Help • Terms & Privacy");
        jLabel5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel5MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel5MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel5MouseExited(evt);
            }
        });
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 570, 670, -1));

        labelUser.setFont(new java.awt.Font("Questrial", 0, 28)); // NOI18N
        labelUser.setForeground(new java.awt.Color(11, 77, 212));
        labelUser.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelUser.setText("Recent Logged");
        getContentPane().add(labelUser, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 360, 300, -1));

        jLabel7.setFont(new java.awt.Font("Source Sans Pro", 0, 16)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(11, 77, 212));
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setText("Click on an image to login");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 160, 670, -1));

        imgUser1.setPreferredSize(new java.awt.Dimension(100, 100));

        javax.swing.GroupLayout imgUser1Layout = new javax.swing.GroupLayout(imgUser1);
        imgUser1.setLayout(imgUser1Layout);
        imgUser1Layout.setHorizontalGroup(
            imgUser1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        imgUser1Layout.setVerticalGroup(
            imgUser1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        getContentPane().add(imgUser1, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 240, -1, -1));

        jLabel8.setFont(new java.awt.Font("Questrial", 0, 32)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(11, 77, 212));
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel8.setText("Recent Logged");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(439, 120, 670, -1));

        labelUser2.setFont(new java.awt.Font("Questrial", 0, 28)); // NOI18N
        labelUser2.setForeground(new java.awt.Color(11, 77, 212));
        labelUser2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelUser2.setText("Recent Logged");
        getContentPane().add(labelUser2, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 360, 300, -1));

        javax.swing.GroupLayout imgUser2Layout = new javax.swing.GroupLayout(imgUser2);
        imgUser2.setLayout(imgUser2Layout);
        imgUser2Layout.setHorizontalGroup(
            imgUser2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        imgUser2Layout.setVerticalGroup(
            imgUser2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        getContentPane().add(imgUser2, new org.netbeans.lib.awtextra.AbsoluteConstraints(880, 240, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void emailFieldFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_emailFieldFocusGained
        emailField.setText("");
    }//GEN-LAST:event_emailFieldFocusGained

    private void passwordFieldFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_passwordFieldFocusGained
        passwordField.setText("");
        passwordField.setForeground(Color.yellow);
    }//GEN-LAST:event_passwordFieldFocusGained

    private void btnEnterMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnEnterMouseEntered
        setCursor(Cursor.HAND_CURSOR);
    }//GEN-LAST:event_btnEnterMouseEntered

    private void btnSignUpMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSignUpMouseEntered
        setCursor(Cursor.HAND_CURSOR);
    }//GEN-LAST:event_btnSignUpMouseEntered

    private void btnEnterMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnEnterMouseExited
        setCursor(Cursor.DEFAULT_CURSOR);
    }//GEN-LAST:event_btnEnterMouseExited

    private void btnSignUpMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSignUpMouseExited
        setCursor(Cursor.DEFAULT_CURSOR);
    }//GEN-LAST:event_btnSignUpMouseExited

    private void jLabel5MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel5MouseEntered
        setCursor(Cursor.HAND_CURSOR);
    }//GEN-LAST:event_jLabel5MouseEntered

    private void jLabel5MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel5MouseExited
        setCursor(DEFAULT_CURSOR);
    }//GEN-LAST:event_jLabel5MouseExited

    private void jLabel5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel5MouseClicked
        JOptionPane.showMessageDialog(null, "App developed by Angel D'arte <github:@angelostd>");
    }//GEN-LAST:event_jLabel5MouseClicked

    private void btnEnterMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnEnterMouseClicked
        if (Pattern.compile("^(.+)@(.+)$").matcher(emailField.getText()).matches()) {
            boolean nope = false;
            for (User user : users) {
                nope = false;
                if (emailField.getText().equals(user.getEmail()) && String.valueOf(passwordField.getPassword()).equals(user.getPassword()) && user.isIsActive()) {
                    new ForumFrame(user.getId()).setVisible(true);
                    dispose();
                    if (!user.isIsAdmin() && jCheckBox1.isSelected()) {
                        JSONManager.setRecentUsers(user);
                    }
                    break;
                } else if (!user.isIsActive() && emailField.getText().equals(user.getEmail())) {
                    JOptionPane.showMessageDialog(null, "You are trying to access from a BANNED account");
                    break;
                } else if (emailField.getText().equals(user.getEmail()) && user.isIsActive()) {
                    JOptionPane.showMessageDialog(null, "Incorrect password");
                    break;
                } else {
                    nope = true;
                }
            }
            if (nope) {
                JOptionPane.showMessageDialog(null, "The email you entered isn’t connected to an account");
            }
        } else {
            JOptionPane.showMessageDialog(null, "Please enter a valid email");
        }
    }//GEN-LAST:event_btnEnterMouseClicked

    private void btnSignUpMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSignUpMouseClicked
        dispose();
        new RegisterFrame().setVisible(true);
    }//GEN-LAST:event_btnSignUpMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LoginFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LoginFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LoginFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LoginFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new LoginFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel btnEnter;
    private javax.swing.JLabel btnSignUp;
    private javax.swing.JTextField emailField;
    private org.edisoncor.gui.panel.PanelImage imgUser1;
    private org.edisoncor.gui.panel.PanelImage imgUser2;
    private javax.swing.JCheckBox jCheckBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JLabel labelUser;
    private javax.swing.JLabel labelUser2;
    private org.edisoncor.gui.panel.Panel panel1;
    private javax.swing.JPasswordField passwordField;
    // End of variables declaration//GEN-END:variables

    private void displayRecentUsers() {
        Image originalImg2 = new ImageIcon(recentUsers.get(0).getPfpPath()).getImage();
        imgUser2.setIcon(new ImageIcon(originalImg2.getScaledInstance(100, 100, Image.SCALE_SMOOTH)));
        labelUser2.setText(recentUsers.get(0).getName());

        Image originalImg = new ImageIcon(recentUsers.get(1).getPfpPath()).getImage();
        imgUser1.setIcon(new ImageIcon(originalImg.getScaledInstance(100, 100, Image.SCALE_SMOOTH)));
        labelUser.setText(recentUsers.get(1).getName());

        MouseListener listener = new MouseListener() {
            @Override
            public void mouseClicked(MouseEvent e) {
            }

            @Override
            public void mousePressed(MouseEvent e) {
            }

            @Override
            public void mouseReleased(MouseEvent e) {
            }

            @Override
            public void mouseEntered(MouseEvent e) {
                setCursor(Cursor.HAND_CURSOR);
            }

            @Override
            public void mouseExited(MouseEvent e) {
                setCursor(DEFAULT_CURSOR);
            }
        };

        imgUser1.addMouseListener(listener);
        imgUser1.addMouseListener(new MouseAdapter() {
            @Override
            public void mouseClicked(MouseEvent e) {
                new ForumFrame(recentUsers.get(1).getId()).setVisible(true);
                dispose();
            }
        });

        imgUser2.addMouseListener(listener);
        imgUser2.addMouseListener(new MouseAdapter() {
            @Override
            public void mouseClicked(MouseEvent e) {
                new ForumFrame(recentUsers.get(0).getId()).setVisible(true);
                dispose();
            }
        });

        repaint();
    }
}
