/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.tap_u3tv.ui;

import com.mycompany.tap_u3tv.classes.DBManager;
import com.mycompany.tap_u3tv.classes.User;
import java.awt.Color;
import java.awt.Image;
import java.nio.file.Paths;
import java.util.ArrayList;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

/**
 *
 * @author angel
 */
public class ProfileFrame extends javax.swing.JFrame {

    private ArrayList<User> users = new ArrayList<>();
    private User userToDisplay;
    private int userLoggedId;

    /**
     * Creates new form RegisterFrame
     */
    public ProfileFrame() {
        initComponents();
    }

    public ProfileFrame(int userId, int userLogged) {
        initComponents();
        setLocationRelativeTo(null);

        try {
            users = DBManager.getUsers();
            userLoggedId = userLogged;
            for (User user : users) {
                if (user.getId() == userId) {
                    userToDisplay = user;
                }
            }
        } catch (Exception e) {
            e.printStackTrace();
        }

        displayUserInfo(userId, userLogged);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panel1 = new org.edisoncor.gui.panel.Panel();
        panelRound2 = new org.edisoncor.gui.panel.PanelRound();
        panelRound1 = new org.edisoncor.gui.panel.PanelRound();
        jPanel1 = new javax.swing.JPanel();
        imgUser = new org.edisoncor.gui.panel.PanelImage();
        labelUser = new javax.swing.JLabel();
        btnDelete = new javax.swing.JLabel();
        labelLikes = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        labelEmail = new javax.swing.JLabel();
        labelThemes = new javax.swing.JLabel();
        labelComments = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setResizable(false);
        setSize(new java.awt.Dimension(1512, 982));
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        panel1.setColorPrimario(new java.awt.Color(16, 81, 213));
        panel1.setColorSecundario(new java.awt.Color(47, 132, 252));
        panel1.setPreferredSize(new java.awt.Dimension(1112, 682));
        panel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        panelRound2.setAnchoDeBorde(6.0F);
        panelRound2.setColorDeBorde(new java.awt.Color(255, 255, 255));
        panelRound2.setColorPrimario(new java.awt.Color(255, 255, 255));
        panelRound2.setColorSecundario(new java.awt.Color(255, 255, 255));
        panelRound2.setOpaque(false);
        panel1.add(panelRound2, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 560, 540, 60));

        panelRound1.setAnchoDeBorde(6.0F);
        panelRound1.setColorDeBorde(new java.awt.Color(255, 255, 255));
        panelRound1.setColorPrimario(new java.awt.Color(255, 255, 255));
        panelRound1.setColorSecundario(new java.awt.Color(255, 255, 255));
        panelRound1.setOpaque(false);
        panel1.add(panelRound1, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 20, 540, 70));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        imgUser.setOpaque(false);
        imgUser.setPreferredSize(new java.awt.Dimension(100, 100));
        imgUser.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                imgUserMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                imgUserMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                imgUserMouseExited(evt);
            }
        });

        javax.swing.GroupLayout imgUserLayout = new javax.swing.GroupLayout(imgUser);
        imgUser.setLayout(imgUserLayout);
        imgUserLayout.setHorizontalGroup(
            imgUserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        imgUserLayout.setVerticalGroup(
            imgUserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        jPanel1.add(imgUser, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 40, -1, -1));

        labelUser.setFont(new java.awt.Font("Questrial", 0, 28)); // NOI18N
        labelUser.setForeground(new java.awt.Color(11, 77, 212));
        labelUser.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelUser.setText("Recent Logged");
        jPanel1.add(labelUser, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 160, 300, -1));

        btnDelete.setFont(new java.awt.Font("Questrial", 0, 32)); // NOI18N
        btnDelete.setForeground(new java.awt.Color(222, 157, 155));
        btnDelete.setIcon(new javax.swing.ImageIcon("C:\\Users\\angel\\Pictures\\Therum\\i-delete.png")); // NOI18N
        btnDelete.setText("Delete user");
        btnDelete.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnDeleteMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnDeleteMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnDeleteMouseExited(evt);
            }
        });
        jPanel1.add(btnDelete, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 420, -1, -1));

        labelLikes.setFont(new java.awt.Font("Questrial", 0, 24)); // NOI18N
        labelLikes.setForeground(new java.awt.Color(0, 0, 0));
        labelLikes.setText("numberlarge");
        jPanel1.add(labelLikes, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 340, 190, -1));

        jLabel3.setFont(new java.awt.Font("Questrial", 0, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(140, 140, 140));
        jLabel3.setText("Total themes:");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 260, -1, -1));

        jLabel4.setFont(new java.awt.Font("Questrial", 0, 24)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(140, 140, 140));
        jLabel4.setText("Total comments:");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 300, -1, -1));

        jLabel5.setFont(new java.awt.Font("Questrial", 0, 24)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(140, 140, 140));
        jLabel5.setText("Total likes:");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 340, -1, -1));

        jLabel6.setFont(new java.awt.Font("Questrial", 0, 24)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(140, 140, 140));
        jLabel6.setText("Email:");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 220, -1, -1));

        labelEmail.setFont(new java.awt.Font("Questrial", 0, 24)); // NOI18N
        labelEmail.setForeground(new java.awt.Color(0, 0, 0));
        labelEmail.setText("email_large_test@email.com");
        jPanel1.add(labelEmail, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 220, 320, -1));

        labelThemes.setFont(new java.awt.Font("Questrial", 0, 24)); // NOI18N
        labelThemes.setForeground(new java.awt.Color(0, 0, 0));
        labelThemes.setText("numberlarge");
        jPanel1.add(labelThemes, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 260, 220, -1));

        labelComments.setFont(new java.awt.Font("Questrial", 0, 24)); // NOI18N
        labelComments.setForeground(new java.awt.Color(0, 0, 0));
        labelComments.setText("numberlarge");
        jPanel1.add(labelComments, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 300, 190, -1));

        panel1.add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 60, 540, 510));

        getContentPane().add(panel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1090, 650));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        new ForumFrame(userLoggedId).setVisible(true);
    }//GEN-LAST:event_formWindowClosing

    private void btnDeleteMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnDeleteMouseEntered
        setCursor(HAND_CURSOR);
    }//GEN-LAST:event_btnDeleteMouseEntered

    private void btnDeleteMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnDeleteMouseExited
        setCursor(DEFAULT_CURSOR);
    }//GEN-LAST:event_btnDeleteMouseExited

    private void btnDeleteMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnDeleteMouseClicked
        try {
            if (!(DBManager.checkUser(userToDisplay.getId()) == 0)) {
                if (JOptionPane.showConfirmDialog(null, "Are you SURE you want to BAN this user?", "Confirm", JOptionPane.YES_NO_OPTION) == JOptionPane.YES_OPTION) {
                    if (DBManager.deactivateUser(userToDisplay) > 0) {
                        JOptionPane.showMessageDialog(null, "[user disabled]");
                    } else {
                        JOptionPane.showMessageDialog(null, "[there was an error]");
                    }
                }
            } else {
                if (JOptionPane.showConfirmDialog(null, "Are you SURE you want to UNBAN this user?", "Confirm", JOptionPane.YES_NO_OPTION) == JOptionPane.YES_OPTION) {
                    if (DBManager.activeuser(userToDisplay.getId()) > 0) {
                        JOptionPane.showMessageDialog(null, "[user activaded]");
                    } else {
                        JOptionPane.showMessageDialog(null, "[there was an error]");
                    }
                }
            }
        } catch (Exception e) {
            e.printStackTrace();
        }
    }//GEN-LAST:event_btnDeleteMouseClicked

    private void imgUserMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_imgUserMouseEntered
        if (userToDisplay.getId() == userLoggedId) {
            setCursor(HAND_CURSOR);
            imgUser.setIcon(new ImageIcon(Paths.get("C:\\Users\\angel\\Pictures\\Therum\\pfp-hover.png").toAbsolutePath().toString()));
            repaint();
        }
    }//GEN-LAST:event_imgUserMouseEntered

    private void imgUserMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_imgUserMouseExited
        setCursor(DEFAULT_CURSOR);
        imgUser.setIcon(new ImageIcon(new ImageIcon(userToDisplay.getPfpPath()).getImage().getScaledInstance(100, 100, Image.SCALE_SMOOTH)));
        repaint();
    }//GEN-LAST:event_imgUserMouseExited

    private void imgUserMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_imgUserMouseClicked
        if (userToDisplay.getId() == userLoggedId) {
            new ProfilePhotoChooser(userToDisplay.getId()).setVisible(true);
        }
    }//GEN-LAST:event_imgUserMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ProfileFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ProfileFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ProfileFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ProfileFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ProfileFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel btnDelete;
    private org.edisoncor.gui.panel.PanelImage imgUser;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel labelComments;
    private javax.swing.JLabel labelEmail;
    private javax.swing.JLabel labelLikes;
    private javax.swing.JLabel labelThemes;
    private javax.swing.JLabel labelUser;
    private org.edisoncor.gui.panel.Panel panel1;
    private org.edisoncor.gui.panel.PanelRound panelRound1;
    private org.edisoncor.gui.panel.PanelRound panelRound2;
    // End of variables declaration//GEN-END:variables

    private void displayUserInfo(int userId, int userLogged) {
        for (User user : users) {
            if (user.getId() == userId) {
                imgUser.setIcon(new ImageIcon(new ImageIcon(userToDisplay.getPfpPath()).getImage().getScaledInstance(100, 100, Image.SCALE_SMOOTH)));

                labelUser.setText(user.getName());
                labelEmail.setText(user.getEmail());
                try {
                    labelThemes.setText(String.valueOf(DBManager.countUserPost(user.getId())));
                    labelComments.setText(String.valueOf(DBManager.countUserComments(user.getId())));
                    labelLikes.setText(String.valueOf(DBManager.countUserLikes(user.getId())));
                } catch (Exception e) {
                    e.printStackTrace();
                }
            }
        }
        for (User user : users) {
            if (user.getId() == userLogged && user.isIsAdmin()) {
                btnDelete.setEnabled(true);
                btnDelete.setVisible(true);
                if (!userToDisplay.isIsActive()) {
                    btnDelete.setText("REACTIVATE USER");
                    btnDelete.setForeground(Color.decode("#94c98f"));
                    btnDelete.setIcon(new ImageIcon(Paths.get("C:\\Users\\angel\\Pictures\\Therum\\i-up.png").toAbsolutePath().toString()));
                }
                break;
            } else {
                btnDelete.setEnabled(false);
                btnDelete.setVisible(false);
            }
        }
    }
}
