/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.tap_u3tv.ui;

import com.mycompany.tap_u3tv.classes.DBManager;
import com.mycompany.tap_u3tv.classes.User;
import java.awt.Cursor;
import java.util.ArrayList;
import java.util.regex.Pattern;
import javax.swing.JOptionPane;

/**
 *
 * @author angel
 */
public class RegisterFrame extends javax.swing.JFrame {

    private ArrayList<User> users;

    /**
     * Creates new form RegisterFrame
     */
    public RegisterFrame() {
        initComponents();
        setLocationRelativeTo(null);

        try {
            users = DBManager.getUsers();
        } catch (Exception e) {
            e.printStackTrace();
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panel1 = new org.edisoncor.gui.panel.Panel();
        panelRound2 = new org.edisoncor.gui.panel.PanelRound();
        panelRound1 = new org.edisoncor.gui.panel.PanelRound();
        jPanel1 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        fieldUsername = new javax.swing.JTextField();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel5 = new javax.swing.JLabel();
        fieldEmail = new javax.swing.JTextField();
        jSeparator2 = new javax.swing.JSeparator();
        jLabel8 = new javax.swing.JLabel();
        jSeparator3 = new javax.swing.JSeparator();
        fieldPassword = new javax.swing.JPasswordField();
        btnSignUp = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(1112, 682));
        setResizable(false);
        setSize(new java.awt.Dimension(1512, 982));
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        panel1.setColorPrimario(new java.awt.Color(16, 81, 213));
        panel1.setColorSecundario(new java.awt.Color(47, 132, 252));
        panel1.setPreferredSize(new java.awt.Dimension(1112, 682));
        panel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        panelRound2.setAnchoDeBorde(6.0F);
        panelRound2.setColorDeBorde(new java.awt.Color(255, 255, 255));
        panelRound2.setColorPrimario(new java.awt.Color(255, 255, 255));
        panelRound2.setColorSecundario(new java.awt.Color(255, 255, 255));
        panelRound2.setOpaque(false);
        panel1.add(panelRound2, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 560, 540, 60));

        panelRound1.setAnchoDeBorde(6.0F);
        panelRound1.setColorDeBorde(new java.awt.Color(255, 255, 255));
        panelRound1.setColorPrimario(new java.awt.Color(255, 255, 255));
        panelRound1.setColorSecundario(new java.awt.Color(255, 255, 255));
        panelRound1.setOpaque(false);
        panel1.add(panelRound1, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 20, 540, 70));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel6.setFont(new java.awt.Font("Questrial", 0, 24)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(11, 77, 212));
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("It's quick and easy");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 60, 340, -1));

        jLabel7.setFont(new java.awt.Font("Source Sans Pro SemiBold", 0, 32)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(11, 77, 212));
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setText("Sign Up");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 20, 250, -1));

        jLabel4.setFont(new java.awt.Font("Questrial", 0, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(11, 77, 212));
        jLabel4.setText("Username");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 100, 200, 30));

        fieldUsername.setBackground(new java.awt.Color(255, 255, 255));
        fieldUsername.setFont(new java.awt.Font("Questrial", 0, 18)); // NOI18N
        fieldUsername.setForeground(new java.awt.Color(11, 77, 212));
        fieldUsername.setBorder(null);
        jPanel1.add(fieldUsername, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 130, 390, -1));

        jSeparator1.setBackground(new java.awt.Color(11, 77, 212));
        jPanel1.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 150, 390, 10));

        jLabel5.setFont(new java.awt.Font("Questrial", 0, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(11, 77, 212));
        jLabel5.setText("Email");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 190, 200, 30));

        fieldEmail.setBackground(new java.awt.Color(255, 255, 255));
        fieldEmail.setFont(new java.awt.Font("Questrial", 0, 18)); // NOI18N
        fieldEmail.setForeground(new java.awt.Color(11, 77, 212));
        fieldEmail.setBorder(null);
        jPanel1.add(fieldEmail, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 220, 390, -1));

        jSeparator2.setBackground(new java.awt.Color(11, 77, 212));
        jPanel1.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 240, 390, 10));

        jLabel8.setFont(new java.awt.Font("Questrial", 0, 18)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(11, 77, 212));
        jLabel8.setText("Password");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 290, 200, 30));

        jSeparator3.setBackground(new java.awt.Color(11, 77, 212));
        jPanel1.add(jSeparator3, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 340, 390, 10));

        fieldPassword.setBackground(new java.awt.Color(255, 255, 255));
        fieldPassword.setFont(new java.awt.Font("Questrial", 0, 18)); // NOI18N
        fieldPassword.setForeground(new java.awt.Color(11, 77, 212));
        fieldPassword.setBorder(null);
        jPanel1.add(fieldPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 320, 390, -1));

        btnSignUp.setIcon(new javax.swing.ImageIcon("C:\\Users\\angel\\Pictures\\Therum\\signup-btn.png")); // NOI18N
        btnSignUp.setPreferredSize(new java.awt.Dimension(78, 48));
        btnSignUp.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnSignUpMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnSignUpMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnSignUpMouseExited(evt);
            }
        });
        jPanel1.add(btnSignUp, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 420, 360, 50));

        panel1.add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 60, 540, 510));

        getContentPane().add(panel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1120, 650));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        new LoginFrame().setVisible(true);
    }//GEN-LAST:event_formWindowClosing

    private void btnSignUpMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSignUpMouseClicked
        if (Pattern.compile("^(.+)@(.+)$").matcher(fieldEmail.getText()).matches()) {
            for (User user : users) {
                if (fieldEmail.getText().equals(user.getEmail())) {
                    JOptionPane.showMessageDialog(null, "This email is already registered");
                }
            }
            try {
                if (DBManager.createUser(fieldUsername.getText(), fieldEmail.getText(), String.valueOf(fieldPassword.getPassword())) > 0) {
                    JOptionPane.showMessageDialog(null, "User created succesfully :]");
                    dispose();
                    new LoginFrame().setVisible(true);
                }
            } catch (Exception e) {
                e.printStackTrace();
            }
        } else {
            JOptionPane.showMessageDialog(null, "Please enter a valid email");
        }
    }//GEN-LAST:event_btnSignUpMouseClicked

    private void btnSignUpMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSignUpMouseEntered
        setCursor(Cursor.HAND_CURSOR);
    }//GEN-LAST:event_btnSignUpMouseEntered

    private void btnSignUpMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSignUpMouseExited
        setCursor(Cursor.DEFAULT_CURSOR);
    }//GEN-LAST:event_btnSignUpMouseExited

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(RegisterFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(RegisterFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(RegisterFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(RegisterFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new RegisterFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel btnSignUp;
    private javax.swing.JTextField fieldEmail;
    private javax.swing.JPasswordField fieldPassword;
    private javax.swing.JTextField fieldUsername;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private org.edisoncor.gui.panel.Panel panel1;
    private org.edisoncor.gui.panel.PanelRound panelRound1;
    private org.edisoncor.gui.panel.PanelRound panelRound2;
    // End of variables declaration//GEN-END:variables
}
