/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.tap_u3tv.ui;

import com.mycompany.tap_u3tv.classes.Comment;
import com.mycompany.tap_u3tv.classes.DBManager;
import com.mycompany.tap_u3tv.classes.Theme;
import com.mycompany.tap_u3tv.classes.User;
import java.awt.GridLayout;
import java.awt.Image;
import java.nio.file.Paths;
import java.util.ArrayList;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

/**
 *
 * @author angel
 */
public class ResponsesFrame extends javax.swing.JFrame {

    private ArrayList<User> users;
    private User userLogged;
    private User userWhoPosted;
    private Theme post;
    private ArrayList<Comment> comments;
    private GridLayout gridLayout = new GridLayout(1, 1);

    /**
     * Creates new form ForumFrame
     */
    public ResponsesFrame() {
        initComponents();
    }

    public ResponsesFrame(int userId, Theme post) {
        initComponents();
        setLocationRelativeTo(null);

        try {
            users = DBManager.getUsers();
            users.stream().filter(user -> user.getId() == userId).forEach(user -> this.userLogged = user);
            users.stream().filter(user -> user.getId() == post.getUserdId()).forEach(user -> this.userWhoPosted = user);
            this.post = post;
            comments = DBManager.readCommentsFromPost(post.getId());

            container.setLayout(gridLayout);
            scrollPane.getVerticalScrollBar().setUnitIncrement(16);
        } catch (Exception e) {
            e.printStackTrace();
        }

        display();
        displayComments();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        scrollPane = new javax.swing.JScrollPane();
        container = new javax.swing.JPanel();
        btnNewComm = new javax.swing.JLabel();
        header = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        iconLikes = new org.edisoncor.gui.panel.PanelImage();
        imgUser = new org.edisoncor.gui.panel.PanelImage();
        labelLikes = new javax.swing.JLabel();
        labelTime = new javax.swing.JLabel();
        labelUsername = new javax.swing.JLabel();
        footer = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));
        setPreferredSize(new java.awt.Dimension(1110, 660));
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        scrollPane.setBackground(new java.awt.Color(251, 251, 251));
        scrollPane.setBorder(null);
        scrollPane.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_ALWAYS);
        scrollPane.setHorizontalScrollBar(null);
        scrollPane.setPreferredSize(new java.awt.Dimension(1110, 360));

        container.setBackground(new java.awt.Color(238, 238, 238));

        javax.swing.GroupLayout containerLayout = new javax.swing.GroupLayout(container);
        container.setLayout(containerLayout);
        containerLayout.setHorizontalGroup(
            containerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1097, Short.MAX_VALUE)
        );
        containerLayout.setVerticalGroup(
            containerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 560, Short.MAX_VALUE)
        );

        scrollPane.setViewportView(container);

        getContentPane().add(scrollPane, new org.netbeans.lib.awtextra.AbsoluteConstraints(8, 220, 1110, 360));

        btnNewComm.setIcon(new javax.swing.ImageIcon("C:\\Users\\angel\\Pictures\\Therum\\new-comm-btn.png")); // NOI18N
        btnNewComm.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnNewCommMouseClicked(evt);
            }
        });
        getContentPane().add(btnNewComm, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 580, -1, -1));

        header.setBackground(new java.awt.Color(255, 255, 255));
        header.setForeground(new java.awt.Color(255, 255, 255));

        jScrollPane1.setBackground(new java.awt.Color(255, 255, 255));
        jScrollPane1.setBorder(null);
        jScrollPane1.setForeground(new java.awt.Color(0, 0, 0));
        jScrollPane1.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        jScrollPane1.setOpaque(false);
        jScrollPane1.setPreferredSize(new java.awt.Dimension(1030, 82));

        jTextArea1.setEditable(false);
        jTextArea1.setBackground(new java.awt.Color(255, 255, 255));
        jTextArea1.setColumns(20);
        jTextArea1.setFont(new java.awt.Font("Questrial", 0, 16)); // NOI18N
        jTextArea1.setForeground(new java.awt.Color(0, 0, 0));
        jTextArea1.setLineWrap(true);
        jTextArea1.setRows(5);
        jTextArea1.setText("Lorem ipsum dolor sit amet, consectetur adipiscing elit. Proin purus magna, aliquet eu lectus a, porttitor bibendum ipsum. Pellentesque in tortor maximus turpis sagittis consectetur. Ut semper magna enim, et convallis felis suscipit eget. Sed placerat velit tellus, tempor egestas nisi volutpat quis. Curabitur libero aliquam venenatis. Praesent.");
        jTextArea1.setWrapStyleWord(true);
        jTextArea1.setBorder(null);
        jTextArea1.setPreferredSize(new java.awt.Dimension(1030, 82));
        jScrollPane1.setViewportView(jTextArea1);

        iconLikes.setBackground(new java.awt.Color(255, 255, 255));
        iconLikes.setForeground(new java.awt.Color(140, 140, 140));
        iconLikes.setFont(new java.awt.Font("Questrial", 0, 20)); // NOI18N
        iconLikes.setIcon(new javax.swing.ImageIcon("C:\\Users\\angel\\Pictures\\Therum\\i-heart.png")); // NOI18N
        iconLikes.setPreferredSize(new java.awt.Dimension(30, 30));
        iconLikes.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                iconLikesMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout iconLikesLayout = new javax.swing.GroupLayout(iconLikes);
        iconLikes.setLayout(iconLikesLayout);
        iconLikesLayout.setHorizontalGroup(
            iconLikesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 30, Short.MAX_VALUE)
        );
        iconLikesLayout.setVerticalGroup(
            iconLikesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 30, Short.MAX_VALUE)
        );

        imgUser.setOpaque(false);
        imgUser.setPreferredSize(new java.awt.Dimension(64, 64));
        imgUser.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                imgUserMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout imgUserLayout = new javax.swing.GroupLayout(imgUser);
        imgUser.setLayout(imgUserLayout);
        imgUserLayout.setHorizontalGroup(
            imgUserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 64, Short.MAX_VALUE)
        );
        imgUserLayout.setVerticalGroup(
            imgUserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 64, Short.MAX_VALUE)
        );

        labelLikes.setBackground(new java.awt.Color(255, 255, 255));
        labelLikes.setFont(new java.awt.Font("Questrial", 0, 20)); // NOI18N
        labelLikes.setForeground(new java.awt.Color(140, 140, 140));
        labelLikes.setText("180 Likes");

        labelTime.setFont(new java.awt.Font("Questrial", 0, 16)); // NOI18N
        labelTime.setForeground(new java.awt.Color(140, 140, 140));
        labelTime.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        labelTime.setText("Mon Apr 03 22:40:33 CST 2023");

        labelUsername.setFont(new java.awt.Font("Questrial", 0, 32)); // NOI18N
        labelUsername.setForeground(new java.awt.Color(30, 30, 30));
        labelUsername.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        labelUsername.setText(" adavid.tinocod@gmai.com");
        labelUsername.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                labelUsernameMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout headerLayout = new javax.swing.GroupLayout(header);
        header.setLayout(headerLayout);
        headerLayout.setHorizontalGroup(
            headerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1110, Short.MAX_VALUE)
            .addGroup(headerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(headerLayout.createSequentialGroup()
                    .addGap(0, 40, Short.MAX_VALUE)
                    .addGroup(headerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(headerLayout.createSequentialGroup()
                            .addComponent(imgUser, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(18, 18, 18)
                            .addGroup(headerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(labelTime, javax.swing.GroupLayout.PREFERRED_SIZE, 570, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(labelUsername, javax.swing.GroupLayout.PREFERRED_SIZE, 590, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 1030, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(headerLayout.createSequentialGroup()
                            .addComponent(iconLikes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(10, 10, 10)
                            .addComponent(labelLikes, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGap(0, 40, Short.MAX_VALUE)))
        );
        headerLayout.setVerticalGroup(
            headerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 220, Short.MAX_VALUE)
            .addGroup(headerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(headerLayout.createSequentialGroup()
                    .addGap(0, 12, Short.MAX_VALUE)
                    .addGroup(headerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(imgUser, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(headerLayout.createSequentialGroup()
                            .addGap(30, 30, 30)
                            .addComponent(labelTime))
                        .addComponent(labelUsername))
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addGroup(headerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(iconLikes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(headerLayout.createSequentialGroup()
                            .addGap(4, 4, 4)
                            .addComponent(labelLikes)))
                    .addGap(0, 12, Short.MAX_VALUE)))
        );

        getContentPane().add(header, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1110, 220));

        footer.setBackground(new java.awt.Color(238, 238, 238));

        javax.swing.GroupLayout footerLayout = new javax.swing.GroupLayout(footer);
        footer.setLayout(footerLayout);
        footerLayout.setHorizontalGroup(
            footerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1110, Short.MAX_VALUE)
        );
        footerLayout.setVerticalGroup(
            footerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 30, Short.MAX_VALUE)
        );

        getContentPane().add(footer, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 630, 1110, 30));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void imgUserMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_imgUserMouseClicked
        new ProfileFrame(post.getUserdId(), userLogged.getId()).setVisible(true);
        dispose();
    }//GEN-LAST:event_imgUserMouseClicked

    private void labelUsernameMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_labelUsernameMouseClicked
        new ProfileFrame(post.getUserdId(), userLogged.getId()).setVisible(true);
        dispose();
    }//GEN-LAST:event_labelUsernameMouseClicked

    private void iconLikesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_iconLikesMouseClicked
        try {
            if (DBManager.countPostLikeFromUser(post.getId(), userLogged.getId()) == 0) {
                if (DBManager.createLikeOnPost(post.getId(), userLogged.getId()) > 0) {
                    System.out.println("Like created :)");
                    display();
                } else {
                    JOptionPane.showMessageDialog(null, "Oops! An error have been occurred while liking this post :c");
                }
            } else {
                if (DBManager.deleteLikeOnPost(post.getId(), userLogged.getId()) > 0) {
                    System.out.println("Like deleted :)");
                    display();
                } else {
                    JOptionPane.showMessageDialog(null, "Oops! An error have been occurred while unliking this post :c");
                }
            }
        } catch (Exception e) {
            e.printStackTrace();
        }
    }//GEN-LAST:event_iconLikesMouseClicked

    private void btnNewCommMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnNewCommMouseClicked
        new NewResponse(userLogged.getId(), post, this).setVisible(true);
    }//GEN-LAST:event_btnNewCommMouseClicked

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        new ForumFrame(userLogged.getId()).setVisible(true);
    }//GEN-LAST:event_formWindowClosing

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ForumFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ForumFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ForumFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ForumFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ForumFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel btnNewComm;
    private javax.swing.JPanel container;
    private javax.swing.JPanel footer;
    private javax.swing.JPanel header;
    private org.edisoncor.gui.panel.PanelImage iconLikes;
    private org.edisoncor.gui.panel.PanelImage imgUser;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JLabel labelLikes;
    private javax.swing.JLabel labelTime;
    private javax.swing.JLabel labelUsername;
    private javax.swing.JScrollPane scrollPane;
    // End of variables declaration//GEN-END:variables

    private void display() {
        Image originalImg = new ImageIcon(userWhoPosted.getPfpPath()).getImage();
        imgUser.setIcon(new ImageIcon(originalImg.getScaledInstance(64, 64, Image.SCALE_SMOOTH)));
        repaint();

        labelUsername.setText(userWhoPosted.getName());
        labelTime.setText(post.getCreatedAt());
        jTextArea1.setText(post.getContent());

        try {
            labelLikes.setText(DBManager.countPostLikes(post.getId()) + " Likes");
            // labelComments.setText(DBManager.countPostComments(post.getId()) + " Comments");
            if (DBManager.countPostLikeFromUser(post.getId(), userLogged.getId()) > 0) {
                iconLikes.setIcon(new ImageIcon(Paths.get("C:\\Users\\angel\\Pictures\\Therum\\i-heart-enable.png").toAbsolutePath().toString()));
            } else {
                iconLikes.setIcon(new ImageIcon(Paths.get("C:\\Users\\angel\\Pictures\\Therum\\i-heart.png").toAbsolutePath().toString()));
            }
        } catch (Exception e) {
            e.printStackTrace();
        }
    }

    private void displayComments() {
        if (comments == null || comments.isEmpty()) {
            System.out.println("No comments to display");
        } else if (users == null || users.isEmpty()) {
            System.out.println("No users with comments to display");
        } else if (post == null) {
            System.out.println("No post available");
        } else {
            container.removeAll();

            comments.stream().filter(comment -> (post.getId() == comment.getThemeId())).forEach(comment -> {
                gridLayout.setRows(gridLayout.getRows() + 1);
                users.stream().filter(user -> (comment.getUserdId() == user.getId())).forEach(user -> {
                    CommentPanel panel = new CommentPanel(comment, user, userLogged, this);
                    container.add(panel);
                });
            });

            container.updateUI();
        }
    }
}
