/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.mycompany.tap_u3tv.ui;

import com.mycompany.tap_u3tv.classes.DBManager;
import com.mycompany.tap_u3tv.classes.Theme;
import com.mycompany.tap_u3tv.classes.User;
import java.awt.Image;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import java.nio.file.Paths;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.SwingUtilities;

/**
 *
 * @author angel
 */
public class ThemePanel extends javax.swing.JPanel {

    private Theme theme;
    private User user;
    private User logged;
    private ForumFrame parent;

    /**
     * Creates new form Theme
     */
    public ThemePanel() {
        initComponents();
    }

    public ThemePanel(Theme theme, User user, User logged, ForumFrame parent) {
        initComponents();

        this.theme = theme;
        this.user = user;
        this.logged = logged;
        this.parent = parent;

        display();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelRound1 = new org.edisoncor.gui.panel.PanelRound();
        labelTime = new javax.swing.JLabel();
        imgUser = new org.edisoncor.gui.panel.PanelImage();
        labelUsername = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        iconLikes = new org.edisoncor.gui.panel.PanelImage();
        labelLikes = new javax.swing.JLabel();
        labelComments = new javax.swing.JLabel();
        iconComments = new org.edisoncor.gui.panel.PanelImage();
        btnRemove = new javax.swing.JLabel();

        setBackground(new java.awt.Color(238, 238, 238));
        setPreferredSize(new java.awt.Dimension(760, 256));

        panelRound1.setBackground(new java.awt.Color(251, 251, 251));
        panelRound1.setColorDeBorde(new java.awt.Color(255, 255, 255));
        panelRound1.setColorPrimario(new java.awt.Color(255, 255, 255));
        panelRound1.setColorSecundario(new java.awt.Color(255, 255, 255));
        panelRound1.setOpaque(false);
        panelRound1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        labelTime.setFont(new java.awt.Font("Questrial", 0, 16)); // NOI18N
        labelTime.setForeground(new java.awt.Color(140, 140, 140));
        labelTime.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        labelTime.setText("Mon Apr 03 22:40:33 CST 2023");
        panelRound1.add(labelTime, new org.netbeans.lib.awtextra.AbsoluteConstraints(112, 60, 570, -1));

        imgUser.setOpaque(false);
        imgUser.setPreferredSize(new java.awt.Dimension(64, 64));
        imgUser.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                imgUserMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout imgUserLayout = new javax.swing.GroupLayout(imgUser);
        imgUser.setLayout(imgUserLayout);
        imgUserLayout.setHorizontalGroup(
            imgUserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        imgUserLayout.setVerticalGroup(
            imgUserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 64, Short.MAX_VALUE)
        );

        panelRound1.add(imgUser, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 30, -1, -1));

        labelUsername.setFont(new java.awt.Font("Questrial", 0, 32)); // NOI18N
        labelUsername.setForeground(new java.awt.Color(30, 30, 30));
        labelUsername.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        labelUsername.setText(" adavid.tinocod@gmai.com");
        labelUsername.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                labelUsernameMouseClicked(evt);
            }
        });
        panelRound1.add(labelUsername, new org.netbeans.lib.awtextra.AbsoluteConstraints(112, 30, 590, -1));

        jScrollPane1.setBackground(new java.awt.Color(255, 255, 255));
        jScrollPane1.setBorder(null);
        jScrollPane1.setForeground(new java.awt.Color(0, 0, 0));
        jScrollPane1.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        jScrollPane1.setOpaque(false);

        jTextArea1.setEditable(false);
        jTextArea1.setBackground(new java.awt.Color(255, 255, 255));
        jTextArea1.setColumns(20);
        jTextArea1.setFont(new java.awt.Font("Questrial", 0, 16)); // NOI18N
        jTextArea1.setForeground(new java.awt.Color(0, 0, 0));
        jTextArea1.setLineWrap(true);
        jTextArea1.setRows(5);
        jTextArea1.setText("Lorem ipsum dolor sit amet, consectetur adipiscing elit. Proin purus magna, aliquet eu lectus a, porttitor bibendum ipsum. Pellentesque in tortor maximus turpis sagittis consectetur. Ut semper magna enim, et convallis felis suscipit eget. Sed placerat velit tellus, tempor egestas nisi volutpat quis. Curabitur libero aliquam venenatis. Praesent.");
        jTextArea1.setBorder(null);
        jScrollPane1.setViewportView(jTextArea1);

        panelRound1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 100, 700, 90));

        iconLikes.setBackground(new java.awt.Color(255, 255, 255));
        iconLikes.setForeground(new java.awt.Color(140, 140, 140));
        iconLikes.setFont(new java.awt.Font("Questrial", 0, 20)); // NOI18N
        iconLikes.setIcon(new javax.swing.ImageIcon("C:\\Users\\angel\\Pictures\\Therum\\i-heart.png")); // NOI18N
        iconLikes.setPreferredSize(new java.awt.Dimension(30, 30));
        iconLikes.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                iconLikesMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout iconLikesLayout = new javax.swing.GroupLayout(iconLikes);
        iconLikes.setLayout(iconLikesLayout);
        iconLikesLayout.setHorizontalGroup(
            iconLikesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 30, Short.MAX_VALUE)
        );
        iconLikesLayout.setVerticalGroup(
            iconLikesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 30, Short.MAX_VALUE)
        );

        panelRound1.add(iconLikes, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 200, -1, -1));

        labelLikes.setBackground(new java.awt.Color(255, 255, 255));
        labelLikes.setFont(new java.awt.Font("Questrial", 0, 20)); // NOI18N
        labelLikes.setForeground(new java.awt.Color(140, 140, 140));
        labelLikes.setText("180 Likes");
        panelRound1.add(labelLikes, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 204, 120, -1));

        labelComments.setBackground(new java.awt.Color(255, 255, 255));
        labelComments.setFont(new java.awt.Font("Questrial", 0, 20)); // NOI18N
        labelComments.setForeground(new java.awt.Color(140, 140, 140));
        labelComments.setText("47 Comments");
        panelRound1.add(labelComments, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 204, 180, -1));

        iconComments.setBackground(new java.awt.Color(255, 255, 255));
        iconComments.setForeground(new java.awt.Color(140, 140, 140));
        iconComments.setFont(new java.awt.Font("Questrial", 0, 20)); // NOI18N
        iconComments.setIcon(new javax.swing.ImageIcon("C:\\Users\\angel\\Pictures\\Therum\\i-comment.png")); // NOI18N
        iconComments.setPreferredSize(new java.awt.Dimension(30, 30));

        javax.swing.GroupLayout iconCommentsLayout = new javax.swing.GroupLayout(iconComments);
        iconComments.setLayout(iconCommentsLayout);
        iconCommentsLayout.setHorizontalGroup(
            iconCommentsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 30, Short.MAX_VALUE)
        );
        iconCommentsLayout.setVerticalGroup(
            iconCommentsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 30, Short.MAX_VALUE)
        );

        panelRound1.add(iconComments, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 200, -1, -1));

        btnRemove.setFont(new java.awt.Font("Questrial", 0, 20)); // NOI18N
        btnRemove.setForeground(new java.awt.Color(252, 67, 52));
        btnRemove.setIcon(new javax.swing.ImageIcon("C:\\Users\\angel\\Pictures\\Therum\\i-remove.png")); // NOI18N
        btnRemove.setText("Erase theme");
        panelRound1.add(btnRemove, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 200, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(panelRound1, javax.swing.GroupLayout.DEFAULT_SIZE, 754, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(panelRound1, javax.swing.GroupLayout.PREFERRED_SIZE, 244, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void imgUserMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_imgUserMouseClicked
        new ProfileFrame(user.getId(), logged.getId()).setVisible(true);
        parent.dispose();
    }//GEN-LAST:event_imgUserMouseClicked

    private void labelUsernameMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_labelUsernameMouseClicked
        new ProfileFrame(user.getId(), logged.getId()).setVisible(true);
    }//GEN-LAST:event_labelUsernameMouseClicked

    private void iconLikesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_iconLikesMouseClicked
        try {
            if (DBManager.countPostLikeFromUser(theme.getId(), logged.getId()) == 0) {
                if (DBManager.createLikeOnPost(theme.getId(), logged.getId()) > 0) {
                    System.out.println("Like created :)");
                    display();
                } else {
                    JOptionPane.showMessageDialog(null, "Oops! An error have been occurred while liking this post :c");
                }
            } else {
                if (DBManager.deleteLikeOnPost(theme.getId(), logged.getId()) > 0) {
                    System.out.println("Like deleted :)");
                    display();
                } else {
                    JOptionPane.showMessageDialog(null, "Oops! An error have been occurred while unliking this post :c");
                }
            }
        } catch (Exception e) {
            e.printStackTrace();
        }
    }//GEN-LAST:event_iconLikesMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel btnRemove;
    private org.edisoncor.gui.panel.PanelImage iconComments;
    private org.edisoncor.gui.panel.PanelImage iconLikes;
    private org.edisoncor.gui.panel.PanelImage imgUser;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JLabel labelComments;
    private javax.swing.JLabel labelLikes;
    private javax.swing.JLabel labelTime;
    private javax.swing.JLabel labelUsername;
    private org.edisoncor.gui.panel.PanelRound panelRound1;
    // End of variables declaration//GEN-END:variables

    private void display() {
        Image originalImg = new ImageIcon(user.getPfpPath()).getImage();
        imgUser.setIcon(new ImageIcon(originalImg.getScaledInstance(64, 64, Image.SCALE_SMOOTH)));
        repaint();

        labelUsername.setText(user.getName());
        labelTime.setText(theme.getCreatedAt());
        jTextArea1.setText(theme.getContent());

        try {
            labelLikes.setText(DBManager.countPostLikes(theme.getId()) + " Likes");
            labelComments.setText(DBManager.countPostComments(theme.getId()) + " Comments");
            if (DBManager.countPostLikeFromUser(theme.getId(), logged.getId()) > 0) {
                iconLikes.setIcon(new ImageIcon(Paths.get("C:\\Users\\angel\\Pictures\\Therum\\i-heart-enable.png").toAbsolutePath().toString()));
            } else {
                iconLikes.setIcon(new ImageIcon(Paths.get("C:\\Users\\angel\\Pictures\\Therum\\i-heart.png").toAbsolutePath().toString()));
            }
        } catch (Exception e) {
            e.printStackTrace();
        }

        if (logged.isIsAdmin()) {
            btnRemove.setEnabled(true);
            btnRemove.setVisible(true);
        } else {
            btnRemove.setEnabled(false);
            btnRemove.setVisible(false);
        }

        btnRemove.addMouseListener(new MouseAdapter() {
            @Override
            public void mouseClicked(MouseEvent e) {
                if (JOptionPane.showConfirmDialog(null, "Are you SURE you want to delete this? \n(It will delete all likes and comments related too)", "Confirm", JOptionPane.YES_NO_OPTION) == JOptionPane.YES_OPTION) {
                    try {
                        if (DBManager.deletePost(theme.getId()) > 0) {
                            JOptionPane.showMessageDialog(null, "Post deleted successfully");
                            parent.dispose();
                            new ForumFrame(logged.getId()).setVisible(true);
                        } else {
                            JOptionPane.showMessageDialog(null, "Oops! An error have been occurred while deleting this post");
                        }
                    } catch (Exception exception) {
                        exception.printStackTrace();
                    }
                }
            }
        });

        MouseAdapter clickOnComments = new MouseAdapter() {
            @Override
            public void mouseClicked(MouseEvent e) {
                parent.dispose();
                new ResponsesFrame(logged.getId(), theme).setVisible(true);
            }
        };
        
        labelComments.addMouseListener(clickOnComments);
        iconComments.addMouseListener(clickOnComments);
    }
}
